---
title: "Pig Data processing and annotation"
date: "`r format(Sys.time(),  '%d %B %Y')`"
author: "Mohamed Hassan"
output: 
  html_notebook:
    theme: cerulean
    toc: true  
    toc_depth: 3
editor_options: 
  markdown: 
    wrap: 72
---



# Downloading (pig data)[https://dreamapp.biomed.au.dk/pigatlas/]
```{r}
Pig_All<-readRDS("/home/lucamannino/R_Projects/scAtlas/Pig/pig_atlas_20221014.rds")
```

```{r}
DimPlot(Pig_All,raster = T)
```

```{r}
#Subset Pig endothelial from SAT Tissue
SAT_Pig <- subset(Pig_All, subset = Tissue == "Adipose-S")
```


```{r}
DimPlot(SAT_Pig,group.by = "Celltype")
```


```{r}
head(SAT_Pig)
```

```{r}
SAT_Pig <- NormalizeData(SAT_Pig, normalization.method = "LogNormalize", scale.factor = 10000)
SAT_Pig <-  FindVariableFeatures(SAT_Pig, selection.method = "vst", nfeatures = 2000)
SAT_Pig <- ScaleData(SAT_Pig,  vars.to.regress = "nCount_RNA")
SAT_Pig <- RunPCA(SAT_Pig, 
                  features = VariableFeatures(object = SAT_Pig))



ElbowPlot(SAT_Pig, ndims = 50)

pct <- SAT_Pig@reductions$pca@stdev / sum(SAT_Pig@reductions$pca@stdev) * 100
cum <- cumsum(pct)
co1 <- which(cum > 90 & pct < 5)[1]
co2 <- sort(which((pct[1:length(pct) -1] - pct[2:length(pct)]) > 0.05), decreasing = T)[1] + 1
pcs = min(co1, co2)
sig_pcs <- 1:pcs


SAT_Pig <- RunUMAP(SAT_Pig, dims = 1:25,reduction = "pca", verbose = FALSE)
SAT_Pig <-FindNeighbors(SAT_Pig, dims = 1:25, reduction = "pca", verbose = FALSE)
SAT_Pig <- FindClusters(SAT_Pig, verbose = FALSE, resolution = 0.3)

```




```{r}
DimPlot(SAT_Pig,label = T)
DimPlot(SAT_Pig,label = T, group.by = "Celltype")

```

```{r}
# SAT_Pig.markers <- FindAllMarkers(SAT_Pig, only.pos = TRUE, min.pct = 0.2, logfc.threshold = 0.2)

SAT_Pig.markers <- FindAllMarkers(SAT_Pig, only.pos = TRUE, 
                                  min.pct = 0.15, logfc.threshold = 0.3)

SAT_Pig.markers %>%
    group_by(cluster) %>%
    slice_max(n = 20, order_by = avg_log2FC)

SAT_Pig.markers %>%
    group_by(cluster) %>%
    top_n(n = 20, wt = avg_log2FC) -> top20

write.xlsx(as.data.frame(SAT_Pig.markers), file="Pig_SAT_markers.xlsx")
```


```{r}
# 0 ASPCs
# 1 ECs
# 2 VSMCs
# 3 ASPCs
# 4 ECS
# 5 Pericytes
# 6 T cells
# 7 B cells
# 8 ASPCs
# 9 Macrophages
# 10 VSMCs
# 11 LECs
# 12 Mast cells

Idents(SAT_Pig) <- SAT_Pig$
new_names = c(
  '0'='ASPCs',
  '1'='Myeloid cells',
  '2'='T and NK cells',
  '3'='Endothelial cells',
  '4'='Adipocytes',
  '5'='Endothelial cells',
  '6'='Mural cells',
  '7'='Myeloid cells',
  '8'='Mast cells',
  '9'='B cells',
  '10'='Adipocytes', 
  '11' = 'Lymphatic Endothelial cells')

SAT_Pig$annotation <- as.character(SAT_Pig$annotation)

SAT_Pig$annotation[grep(pattern = "VSMCs|Pericytes", 
                        x = SAT_Pig$annotation)] <- "Mural cells"
```




```{r}
SAT_Pig$annotation[grep(pattern = "Macrophages", 
                        x = SAT_Pig$annotation)] <- "Macrophages and Monocytes"
SAT_Pig$annotation[grep(pattern = "T cells", 
                        x = SAT_Pig$annotation)] <- "T and NK cells"

SAT_Pig$annotation <- factor(SAT_Pig$annotation, 
                             levels = c("ASPCs", 
                                        "Endothelial cells", 
                                        "Lympahtic endothelial cells",
                                        "Mural cells", 
                                        "Mast cells", 
                                        "Macrophages and Monocytes",
                                        "B cells", "T and NK cells"))

pig_bigobj_cluster_cols <- c("steelblue4", 
                         "red4", 
                         "forestgreen", 
                         "indianred4",
                         "darkslategrey", 
                         "paleturquoise4", 
                         "cadetblue",
                         "violetred4")
DimPlot(SAT_Pig, group.by = "annotation", cols = pig_bigobj_cluster_cols)
```


```{r}
pdf("UMAP_SAT_pig_color_coded_clusters_annotated.pdf", width = 10, height = 10)
DimPlot(SAT_Pig, 
        group.by = "annotation", 
        cols = pig_bigobj_cluster_cols, 
        reduction = "umap", 
        pt.size = 0.1, 
        raster = F) + ggtitle("") + NoLegend() + NoAxes()
dev.off()



pdf("UMAP_SAT_pig_color_coded_clusters_annotated_wLegend.pdf", width = 10, height = 10)
DimPlot(SAT_Pig, 
        group.by = "annotation", 
        cols = pig_bigobj_cluster_cols, 
        reduction = "umap", 
        pt.size = 0.1, 
        raster = F) + ggtitle("") + NoAxes()
dev.off()
```


```{r}
DimPlot(SAT_Pig,group.by = "annotation", label = T) + NoLegend() + DimPlot(SAT_Pig,group.by = "Celltype", label = T) & NoLegend()

```

```{r}
saveRDS(SAT_Pig.markers, "SAT_Pig.RDS")
```



```{r}
SAT_Pig.markers_Final <- FindAllMarkers(SAT_Pig, only.pos = TRUE, 
                                  min.pct = 0.15, logfc.threshold = 0.3)

write.xlsx(as.data.frame(SAT_Pig.markers_Final), "Pig_SAT_markers_Final_for_paper.xlsx")
```



```{r}
Vascular_Pig <- subset(SAT_Pig, subset= annotation %in% 
                         c("Endothelial cells","Mural cells", 
                           "Lympahtic endothelial cells"))
DimPlot(Vascular_Pig, group.by = "annotation")
```



```{r}
DefaultAssay(Vascular_Pig)<- "RNA"
Vascular_Pig <- NormalizeData(Vascular_Pig, normalization.method = "LogNormalize", scale.factor = 10000)
Vascular_Pig <-  FindVariableFeatures(Vascular_Pig, selection.method = "vst", nfeatures = 2000)
Vascular_Pig <- ScaleData(Vascular_Pig,  vars.to.regress = "nCount_RNA")
Vascular_Pig <- RunPCA(Vascular_Pig, features = VariableFeatures(object = Vascular_Pig))


pct <- Vascular_Pig@reductions$pca@stdev / sum(Vascular_Pig@reductions$pca@stdev) * 100
cum <- cumsum(pct)
co1 <- which(cum > 90 & pct < 5)[1]
co2 <- sort(which((pct[1:length(pct) -1] - pct[2:length(pct)]) > 0.05), decreasing = T)[1] + 1
pcs = min(co1, co2)
Vascular_sig_pcs <- 1:pcs

Vascular_Pig <- RunUMAP(Vascular_Pig, dims = 1:19,reduction = "pca", verbose = FALSE)
Vascular_Pig <-FindNeighbors(Vascular_Pig, dims = 1:19, reduction = "pca", verbose = FALSE)
res <- seq(0.1, 1, 0.1)
Vascular_Pig <- FindClusters(Vascular_Pig, verbose = FALSE, resolution = res)
```


```{r}
library(clustree)
clustree::clustree(Vascular_Pig)
```


```{r}
Idents(Vascular_Pig) <- Vascular_Pig$RNA_snn_res.0.3
```



```{r}
UMAPPlot(Vascular_Pig, label = T)
```

```{r}
Vascular_Pig_markers <- FindAllMarkers(Vascular_Pig, only.pos = TRUE, 
                                       min.pct = 0.15, logfc.threshold = 0.3)

write.xlsx(as.data.frame(Vascular_Pig_markers), "Vascular_Pig_markers.xlsx")
```



```{r}
FeaturePlot(Vascular_Pig,c("ARL15","PECAM1","CDH5"),order = T)
```


```{r}
# library(dplyr)
# DefaultAssay(Vascular_Pig) <- "RNA"
# DimPlot(Vascular_Pig,group.by="RNA_snn_res.0.7")
# Vascular_Pig <- SetIdent(Vascular_Pig, value = "RNA_snn_res.0.7")
# Vascular_Pig.markers <- FindAllMarkers(Vascular_Pig, only.pos = TRUE, min.pct = 0.2, logfc.threshold = 0.2)
# Vascular_Pig.markers %>%
#     group_by(cluster) %>%
#     slice_max(n = 20, order_by = avg_log2FC)
# 
# Vascular_Pig.markers %>%
#     group_by(cluster) %>%
#     top_n(n = 20, wt = avg_log2FC) -> top20
# 
# write.table(Vascular_Pig.markers, file="Vascular_Pig.markers.csv", sep = ",")
```



```{r}
# 0 venous
# 1 VSMCs
# 2 Pericytes
# 3 Arterial ECs
# 4 VSMCs
# 5 SubECs ECs
# 6 Capillary ECs
# 7 Lymphatic
# 8 SubECs

Idents(Vascular_Pig) <- Vascular_Pig$RNA_snn_res.0.3

new.clusters.id <- c("Venous Endothelial cells", "VSMCs", "Pericytes", "Arterial Endothelial cells",
                     "VSMCs", "SubECs Endothelial cells", "Capillary Endothelial cells", 
                     "Lymphatic Endothelial cells", "SubEndothelial cells")


names(new.clusters.id) <- levels(Vascular_Pig)

#######################
# Using scCustomize
#######################
Vascular_Pig <- scCustomize::Rename_Clusters(seurat_object = Vascular_Pig,
                                                    new_idents = new.clusters.id)

Vascular_Pig$Vascular_labels <- Vascular_Pig@active.ident
```



```{r}
DimPlot(Vascular_Pig,group.by= "RNA_snn_res.0.3",label=T)
DimPlot(Vascular_Pig,group.by="Vascular_labels",label=T, repel = T)
DimPlot(Vascular_Pig,group.by="Celltype",label=T)
```


```{r}


# pdf("UMAP_Vascular_pig_color_coded_clusters_annotated.pdf", width = 10, height = 10)
DimPlot(Vascular_Pig, 
        group.by = "Vascular_labels", 
        # cols = pig_vascular_cluster_cols, 
        reduction = "umap", 
        pt.size = 0.1, 
        raster = F) + ggtitle("") + NoLegend() + NoAxes()
# dev.off()
```

```{r}
Vascular_Pig$Vascular_labels <- factor(Vascular_Pig$Vascular_labels, 
                                                 levels = c("Venous Endothelial cells", 
                                                            "Capillary Endothelial cells", 
                                                            "Arterial Endothelial cells", 
                                                            "SubEndothelial cells", 
                                                            "Lymphatic Endothelial cells", 
                                                            "Pericytes", "VSMCs"))
pig_vascular_cluster_colors <- c("navy",
                                 "pink3",
                                 "brown3",
                                 "darkgoldenrod",
                                 "forestgreen",
                                 "tan1",
                                 "tan3")


DimPlot(Vascular_Pig, group.by = "Vascular_labels", pt.size = 0.1, 
        raster = F, cols = pig_vascular_cluster_colors)
```

```{r}
pdf("Vascular_Pig_UMAP_colored_wLegend.pdf")
UMAPPlot(Vascular_Pig, group.by = "Vascular_labels", 
         cols = pig_vascular_cluster_colors) + ggtitle("") + NoAxes()
dev.off()

```

```{r}
Idents(Vascular_Pig) <- Vascular_Pig$Vascular_labels

# Running marker genes
DefaultAssay(Vascular_Pig) <-"RNA"

Pig_VascularObj_Markers_final <- FindAllMarkers(Vascular_Pig,
                                only.pos = T,
                                min.pct = 0.15,
                                logfc.threshold = 0.3)

xlsx::write.xlsx(as.data.frame(Pig_VascularObj_Markers_final), 
                "/home/lucamannino/R_Projects/scAtlas/Pig/Pig_VascularObj_Markers_final.xlsx")

```
